### ISSUE TITLE
Lastpass importer does nothing

### ISSUE THREAD

**Issue by oparoz** [nextcloud/passman#233]
Using 2.0.1.

I press on Import, nothing happens.
I press Import again, I get: "Parsed  credentials, starting to import" an a read progress at 100%.

Nothing else happens.

In the Chrome debugger, I land in a VM in a function calling the debugger.

**Comment by brantje** [comment]
That you land in the debugger is a security feature of passman. 
You can turn that off in Admin settings under Additional settings.
![image](https://cloud.githubusercontent.com/assets/2758767/22822562/3c08177e-ef80-11e6-9e5e-771a311abaf9.png)

**Comment by oparoz** [comment]
In the admin panel, I see this:
(Not working atm. OpenSSL has no equivalent of mcrypt_get_key_size())

Does that mean that encryption doesn't work? Changing the method has no effect on that sentence.

**Comment by oparoz** [comment]
Nothing in the Chrome logs

**Comment by oparoz** [comment]
Tough to debug with so little info and if it works for you...

**Comment by animalillo** [comment]
if you give me an example export from last pass i will try to import it and see if it works for me

**Comment by brantje** [comment]
The server side encryption still works. It uses the default aes256-cbc method.
In the future you will be able to change this.

**Comment by oparoz** [comment]
I've just tried with a subset and it worked. What I think the importer doesn't like is all the WLAN XML at the end of the export

```
http://sn,,,"NoteType:Wi-Fi Password
SSID:sjcfreewifi
Password:
Connection Type:ESS
Connection Mode:auto
Authentication:open
Encryption:none
Use 802.1X:false
FIPS Mode:
Key Type:
Protected:
Key Index:
Notes:<?xml version=""1.0""?>
<WLANProfile xmlns=""http://www.microsoft.com/networking/WLAN/profile/v1"">
	<name>sjcfreewifi</name>
	<SSIDConfig>
		<SSID>
			<hex>736A636672656577696669</hex>
			<name>sjcfreewifi</name>
		</SSID>
	</SSIDConfig>
	<connectionType>ESS</connectionType>
	<connectionMode>auto</connectionMode>
	<MSM>
		<security>
			<authEncryption>
				<authentication>open</authentication>
				<encryption>none</encryption>
				<useOneX>false</useOneX>
			</authEncryption>
		</security>
	</MSM>
	<MacRandomization xmlns=""http://www.microsoft.com/networking/WLAN/profile/v3"">
		<enableRandomization>false</enableRandomization>
		<randomizationSeed>831652157</randomizationSeed>
	</MacRandomization>
</WLANProfile>
",sjcfreewifi,,0

```

**Comment by brantje** [comment]
Ouch i doubt our csv parser likes that

**Comment by oparoz** [comment]
Still an error with the subset

```
passman.min.js?v=ed6bde9…:4 TypeError: Cannot read property 'slice' of undefined
    at Object.encrypt (passman.min.js?v=ed6bde9…:10)
    at Object.encrypt (passman.min.js?v=ed6bde9…:11)
    at Object.encryptString (passman.min.js?v=ed6bde9…:28)
    at Object.createCredential (passman.min.js?v=ed6bde9…:28)
    at addCredential (passman.min.js?v=ed6bde9…:30)
    at passman.min.js?v=ed6bde9…:30
    at passman.min.js?v=ed6bde9…:4
    at m.$eval (passman.min.js?v=ed6bde9…:5)
    at m.$digest (passman.min.js?v=ed6bde9…:5)
    at m.$apply (passman.min.js?v=ed6bde9…:5)
```

**Comment by brantje** [comment]
Can you post a few line's of the export, replace passwords with xxxx orso, and users with uuuu.

**Comment by oparoz** [comment]
```
https://demo.pyd.io/,demo,demo,,demo.pyd.io,,0
https://bugs.freedesktop.org,uuuu,pppp,,bugs.freedesktop.org,,0
https://www.drupal.org,uuuu,,drupal.org,,0
https://accounts.odoo.com,uuuu,pppp,,accounts.odoo.com,iS PM,0
https://accounts.odoo.com/web/,uuuu,pppp,,accounts.odoo.com,(none),0
https://cloud.digitalocean.com/registrations/uuuu,pppp,,cloud.digitalocean.com,Business,0
```

**Comment by brantje** [comment]
Small little question, does the csv has headers like
`url,username,password` etc?

**Comment by oparoz** [comment]
Yes `url,username,password,extra,name,grouping,fav`

**Comment by animalillo** [comment]
i'm not even able to import your example export even on lastpass

**Comment by animalillo** [comment]
well, adding the headers made it for lastpass import, let's see if i'm able to import it in passman now xD

**Comment by animalillo** [comment]
can you try this branch, which i hope solves your issue: efef7278b2af87e3ed49f1f5115dd3f448540675

**Comment by Happyfeet01** [comment]
for me the importer do nothing. the Error Console from Internet Explorer showing this:

![image](https://cloud.githubusercontent.com/assets/3295104/22854190/05122f40-f069-11e6-9a72-dd4653bb50a4.png)

**Comment by animalillo** [comment]
@Happyfeet01 what passman version do you have?

**Comment by Happyfeet01** [comment]
Version 2.0.1 @animalillo

**Comment by animalillo** [comment]
We implemented a fix on the branch for v2.0.2, i hope it fixes your problem too!

**Comment by Happyfeet01** [comment]
Thanks @animalillo

**Comment by brantje** [comment]
Closing, 2.0.2 is released. Feel free to open a new issue is the problem still exists.

**Comment by oparoz** [comment]
Still doesn't work for me if I keep the Wifi passwords in. Should I open a separate issue?

**Comment by animalillo** [comment]
Give us more details, or an example not working export

**Comment by brantje** [comment]
The XML in that row is crashing the csv parser, papa-parse. I think it's better to open a issue in the repo of papa-parse. 

An other option is, take it out, import and paste it in the notes field.

**Comment by oparoz** [comment]
@animalillo - I gave an example above.

@brantje - I'll re-open as it just hung in the middle of the import  (without XML). I need to find which entry is causing problems or if it's a timeout issue.

**Comment by animalillo** [comment]
i imported that example flawlessly with my changes, give me a file that is not working

**Comment by Happyfeet01** [comment]
didn´t work for me the importer. when i click on the import button it do nothing. 

Nextcloud.log
```
Method OC_L10N_String::__toString() must return a string value at /var/www/vhosts/larsmueller.net/nextcloud/lib/private/L10N/L10N.php#85
vsprintf(): Too few arguments at /var/www/vhosts/larsmueller.net/nextcloud/lib/private/legacy/l10n/string.php#72
```
and the browserlog

```
jquery-migrate.min.js?v=2cb474d…:2 JQMIGRATE: Migrate is installed, version 1.4.0
passman.min.js?v=2cb474d…:27 Crypto stuff initialized
initEngines @ passman.min.js?v=2cb474d…:27
jquery.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
/index.php/apps/passman/#/:1 Error in event handler for (unknown): TypeError: Cannot read property 'command' of undefined
    at chrome-extension://fhplmmllnpjjlncfjpbbpjadoeijkogc/js/hooks/content.min.js:1:228
/index.php/apps/passman/#/vault/39AAE9C3-AAF7-4883-B332-3D3A3167FC69:1 Error in event handler for (unknown): TypeError: Cannot read property 'command' of undefined
    at chrome-extension://fhplmmllnpjjlncfjpbbpjadoeijkogc/js/hooks/content.min.js:1:228
/index.php/apps/passman/#/vault/39AAE9C3-AAF7-4883-B332-3D3A3167FC69/settings:1 Error in event handler for (unknown): TypeError: Cannot read property 'command' of undefined
    at chrome-extension://fhplmmllnpjjlncfjpbbpjadoeijkogc/js/hooks/content.min.js:1:228
passman.min.js?v=2cb474d…:30 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at m.$scope.fileLoaded [as success] (passman.min.js?v=2cb474d…:30)
    at FileReader.fileReader.onload (passman.min.js?v=2cb474d…:28)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:30 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at m.$scope.fileLoaded [as success] (passman.min.js?v=2cb474d…:30)
    at FileReader.fileReader.onload (passman.min.js?v=2cb474d…:28)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:30 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at m.$scope.fileLoaded [as success] (passman.min.js?v=2cb474d…:30)
    at FileReader.fileReader.onload (passman.min.js?v=2cb474d…:28)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)
passman.min.js?v=2cb474d…:27 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at s._readChunk (passman.min.js?v=2cb474d…:27)
    at s._nextChunk (passman.min.js?v=2cb474d…:27)
    at stream (passman.min.js?v=2cb474d…:27)
    at Object.t [as parse] (passman.min.js?v=2cb474d…:27)
    at Object.PassmanImporter.readCsv (passman.min.js?v=2cb474d…:29)
    at C_Promise.<anonymous> (passman.min.js?v=2cb474d…:29)

```

**Comment by brantje** [comment]
Right, what is that extension `fhplmmllnpjjlncfjpbbpjadoeijkogc`?

**Comment by Happyfeet01** [comment]
@brantje is was an Facebook Video Downloader. But with Internet Explorer ist doesn´t work too

**Comment by brantje** [comment]
Try with firefox or chrome in a private browsing session without addons.
Just tried again, no problems

**Comment by Happyfeet01** [comment]
okay, with **Lastpass pocket** the Export is good and passman tells me "reading success" but it stucks 37/90 Passwords.

**Comment by brantje** [comment]
That indicates there went something wrong during parsing. Can you open up the browser console and paste the error?

**Comment by Happyfeet01** [comment]
here is the error log:

`Uncaught TypeError: Cannot read property 'nodeValue' of undefined
    at Object.PassmanImporter.htmlDecode (passman.min.js:29)
    at C_Promise.<anonymous> (passman.min.js:29)`

**Comment by brantje** [comment]
@Happyfeet01 Can you upload that export, replace the passwords xxxxx orso. Would love to take a look.

**Comment by Happyfeet01** [comment]
[lastpass_backup_lps2.xml.csv.zip](https://github.com/nextcloud/passman/files/779897/lastpass_backup_lps2.xml.csv.zip)

**Comment by brantje** [comment]
Ah i see, the field name is empty for the following row:
![image](https://cloud.githubusercontent.com/assets/2758767/23019583/5c01bfb8-f443-11e6-871a-3be77ffbfc6c.png)
Make sure your credentials have a name.

**Comment by Happyfeet01** [comment]
oh thanks @brantje i look at the complete file

**Comment by brantje** [comment]
Did that work @Happyfeet01 ?

**Comment by brantje** [comment]
If it didn't work you can checkout the `v2.1.1` branch and try the generic csv importer.

**Comment by brantje** [comment]
Closing. V2.1.1 is released.
