### ISSUE TITLE
Invalid Passman certificate

### ISSUE THREAD

**Issue by benoitmasson** [nextcloud/passman#524]
## Bug report

After installing the latest Passman version (2.2.1) on NextCloud 14.0.4:

### Steps to reproduce
Open NextCloud as an admin

### Actual behaviour
An error message in the navbar tells that "There were problems with the code integrity check. More information…"

When clicking the"more information" link, NextCloud says the following:
```Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- passman
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [passman] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)
```

### Configuration
**Passman version**: 2.2.1
**Web server:** Apache 2.4.25
**Database:** MariaDB 10.1.26
**PHP version:** 7.0.27
**cloud server:** Nextcloud 14.0.4

**Comment by Depado** [comment]
Confirmed:

**Passman version:** 2.2.1
**Database:** MySQL 14.14
**Web server:** Caddy 0.10.6
**Cloud server:** Nextcloud 14.0.4
**PHP Version:** 7.2

**Comment by unix0r** [comment]
confirmed for nextcloud 15.0.0 and passman 2.2.1

**Comment by newhinton** [comment]
https://github.com/nextcloud/server/issues/9047

**Comment by Sohn123** [comment]
Confiremd:
Passman version: 2.2.1
Database: SQlite
Web Server: Nginx
Cloud Server: Nextcloud 14.0.4
PHP Version:  7.2

**Comment by newhinton** [comment]
This is an issue with the release-process. We are working on it, and the next release should fix this. Thank you for confirming this bug!

**Comment by AaronADev** [comment]
@newhinton Good morning! Has there been any updates to a fix for this issue?

**Comment by newhinton** [comment]
@AaromADev

heyho! its like 6pm here :D
It will (hopefully) be fixed with the next release, but sadly i can't tell you when, although i hope late januar, early februar

**Comment by AaronADev** [comment]
@newhinton nice! Im in Texas :) Understood, thanks for the update! I'll be checking from time to time.

**Comment by vwbusguy** [comment]
I'm now seeing this here after upgrading Nextcloud to 15.0.1 with Passman version 2.2.1.

**Comment by joergmschulz** [comment]
Uninstall, erase and reinstall from the appstore helped in my case

**Comment by Ricardosgeral** [comment]
uninstalling did not work for me NC15.0.1RC2

**Comment by Ricardosgeral** [comment]
Erasing and reinstall did not work as well

**Comment by sbrodriguez** [comment]
Uninstall, Delete and then Download and Activate from app menu in admin session solved the problem, in my case.

**Comment by e-alfred** [comment]
On 15.0.2, the workaround by removing and reinstalling the app doesn't work anymore.

**Comment by AaronADev** [comment]
Erasing will not work on recent releases. It is a new measure in place to ensure only the right people can push to these apps I believe. It will have to be updated on the the passman side.

**Comment by ChrisB85** [comment]
Same here after upgrading from 14.0.6 to 15.0.2.

**Comment by joluxer** [comment]
Same here after upgrading from 14.0.4 to 14.0.6.

**Comment by murelli146** [comment]
Same after Update from 14.0.6 to 15.0.2

**Comment by nado** [comment]
Just use thumbs up on posts already here, please…

**Comment by wjwieland** [comment]
This needs to be fixed ASAP.  This prevents upgrading of NextCloud on the stable channel.  An app should not stand in the way of a server upgrade, ever.

**Comment by newhinton** [comment]
I agree with you, but i cannot create a release, and therefore i cannot fix this bug. @brantje needs to create a new release, maybe you can also contact him on telegram

**Comment by benoitmasson** [comment]
In my case, the warning did not prevent any upgrade (stable channel too). I still have the warning, but I could upgrade successfully from 14.0.4 to 14.0.6, and now to 15.0.2, and NextCloud and Passman work great.

So apart from esthetic issues, I see no such emergency here. Thanks anyway for taking care of this.

**Comment by Githopp192** [comment]
Same to me after upgrading from 14.0.4 to 14.0.6... beeing on Production Channel... so the Production channel is the new beta testing channel ? :-)

**Comment by Githopp192** [comment]
by the way .. i said i did the Upgrade from 14.0.4 to 14.0.6. and got exact the same error .. but i could solve it .. by disable/uninstall the app and reinstall/enable the App again. Now the Integrity check is fine

**Comment by SyntaxErrol** [comment]
Is reinstallation a simple off/on type of deal that doesn't put the vaults at risk?

**Comment by joergmschulz** [comment]
I reinstalled some times on my test system and never lost data. Even for development branches. BUT be warned to backup first - don't take my word for granted...

**Comment by Cybnate** [comment]
Same problem with certificate on upgrading to 15.04. Application appears to work normal.

**Comment by Githopp192** [comment]
so .. new Information here :-) .. did the Upgrade from NC 14.0.6 to NC 15.0.4 .. got again the Integr. Check error. Now, the Disable/Uninstall and the Re-Install/Enable did not work again .. so i think we'd a fix here ..

**Comment by kikowss** [comment]
Same here Upgrade from 15.0.3 to 15.0.4 Disable/Uninstall and the Re-Install/Enable did not work integrity check error still there.

**Comment by Oclair** [comment]
showing up after an update to 15.0.4 production

**Comment by Ricardosgeral** [comment]
After 15.0.4 for me disappeared, but I've desinstall it before the upgrade

**Comment by Githopp192** [comment]
Ricardosgeral … this was a good hint :-)

So i tried something similar: 

1. Disable the APP
2. De-Install the APP
3. RUN a new Nextcloud cron Job -->
    /bin/php -f /var/www/html/nextcloud/cron.php
4. Wait one, two, three minutes .. 
5. Perform Integrity core check per CLI --> ./occ integrity:check-core
6. Core Check should now be ok
7. Re-Install the APP
8. Enable the APP
9. Perform Integrity core check per CLI --> ./occ integrity:check-core
10. You should be on green now
11. Double check with the GUI - you should be green now

**Comment by AaronADev** [comment]
> Ricardosgeral … this was a good hint :-)
> 
> So i tried something similar:
> 
> 1. Disable the APP
> 2. De-Install the APP
> 3. RUN a new Nextcloud cron Job -->
>    /bin/php -f /var/www/html/nextcloud/cron.php
> 4. Wait one, two, three minutes ..
> 5. Perform Integrity core check per CLI --> ./occ integrity:check-core
> 6. Core Check should now be ok
> 7. Re-Install the APP
> 8. Enable the APP
> 9. Perform Integrity core check per CLI --> ./occ integrity:check-core
> 10. You should be on green now
> 11. Double check with the GUI - you should be green now

Doesn't appear that this method works on my instances. I have the same issue on 4 NextCloud installations all on 15.04. An invalid hash is still returned following that exact procedure. I haven't seen an update for Passman that addresses this issue yet. From what I understand the issue is because applications that any new NextCloud update uses have to have a specific set of keys that were intended to make pushing data to the NextCloud application stores safer, so I don't see this being fixed by running integrity checks prior to or after the installation/de-installation of the application. Other people that use NextCloud outside of my organization state that this method did not work after I passed it on to them so, any other ideas?

**Comment by Githopp192** [comment]
Aaron .. sorry to hear that :-(  .. i think you're right .. into the NC Manual they're saying for a similiar Issue --> "For the calendar exception contact the developer of the application" .. 

I think a manual Scan of the App via "occ integrity:check-app $appid" would only repeat the same kinf of error.

Anyway .. it's a strange behave,that for some instances some approach (that i did) .. is working and for others not !?

--->

Rescans
Rescans are triggered at installation, and by updates. You may run scans manually with the occ command. The first command scans the Nextcloud server files, and the second command scans the named app. There is not yet a command to manually scan all apps:

occ integrity:check-core
occ integrity:check-app $appid

**Comment by Githopp192** [comment]
May .. when i would execute a new 'occ integrity:check-app $appid' .. the error would re-appear on my instance .. so i do not perform that .. :-)

**Comment by kikowss** [comment]
I was able to FIX this annoying error /nextcloud 15.0.4 production/
Thanks to Ricardosgeral  hint
    Disable and de-Install the passman app
	Enable maintenance mode
	sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --on
	RUN 
	sudo -u www-data php -f /var/www/html/nextcloud/cron.php
	RUN
	sudo -u www-data php /var/www/html/nextcloud/occ integrity:check-core
	From web interfce --> settings --> Overview .. run rescan( by click on it :) ) and wait it will open Basic settings page with Background jobs info - last job ran second ago.
	Now check Overview page - All checks passed.
	Disable maintenance mode
	sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --off
	Re-Install and enable the passman app
	Check again Overview page - All checks passed.

**Comment by himpierre** [comment]
although I appreciate your effort @kikowss I would prefer to get this fixed by the app developers. Any news on that @newhinton?

cheers
t.

**Comment by newhinton** [comment]
@everyone
this needs to be fixed by @brantje since it requires a new release, and i cant do that :/. He sadly does not have time to do this, but you may contact him on the telegram group about this issue

**Comment by himpierre** [comment]
Oh man. :-) Do we have to go through this suffering everytime anything breaks?

**Comment by vwbusguy** [comment]
I tried to contact @brantje  on Telegram, but I got a message that he's only accepting messages from "mutual contacts" ...

**Comment by gringo1er** [comment]
Hi everybody. Same issue with the last 15.05 nextcloud version, and with the four days ago commit....
Not a problem for using it...

**Comment by newhinton** [comment]
@gringo1er That was just an automated commit by the translation-bot, no real human commit

@vwbusguy There is a telegram-group, you could write to that
https://t.me/passman_general

albeit @brantje is pretty absent, and he knows that only he can update the app. 
You could check out the other passwords-app for nextcloud, but you'd have to wait for client side encryption there

**Comment by vwbusguy** [comment]
@newhinton - I was able to message him directly on Telegram today.  If he doesn't respond, I'll try that group.

**Comment by vwbusguy** [comment]
I messaged him privately and the telegram group - unfortunately, he doesn't seem to be active much there, either, based on the chat history.

**Comment by vwbusguy** [comment]
@newhinton - Thanks for your work on this. I may indeed end up switching to another app, eventually, given how much trouble it was to get a release for nc15 and for something as simple as this. I'm frustrated because this has so much good potential to it and I'd love to see this mature, but I'm running out of hope for it with the incredible bottleneck on the release process.

**Comment by dersch81** [comment]
> I was able to FIX this annoying error /nextcloud 15.0.4 production/
> Thanks to Githopp192 and Ricardosgeral comments
> Disable and de-Install the passman app
> Enable maintenance mode
> sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --on
> RUN
> sudo -u www-data php -f /var/www/html/nextcloud/cron.php
> RUN
> sudo -u www-data php /var/www/html/nextcloud/occ integrity:check-core
> From web interfce --> settings --> Overview .. run rescan( by click on it :) ) and wait it will open Basic settings page with Background jobs info - last job ran second ago.
> Now check Overview page - All checks passed.
> Disable maintenance mode
> sudo -u www-data php /var/www/html/nextcloud/occ maintenance:mode --off
> Re-Install and enable the passman app
> Check again Overview page - All checks passed.

I've followed your hints. Thanks for that! 

But now i want to reinstall passman. I get the error "Certificate "4120" has been revoked" 
How can i fix that?

regards

**Comment by Mipronimo** [comment]
> But now i want to reinstall passman. I get the error "Certificate "4120" has been revoked"
> How can i fix that?

@earth08 opened an issue in #560. But we did not get a response yet..

**Comment by thenotec** [comment]
The error "Certificate "4120" can be bypassed by manual installation.

Go on folder apps
sudo rm -Rf passman
sudo wget https://github.com/nextcloud/passman/archive/2.2.1.zip
sudo unzip 2.2.1.zip
sudo mv passman-2.2.1 passman
sudo chmod -Rf 755 passman
sudo chown -Rf www-data:www-data passman

Go on application and active extension.
Done!

**Comment by RemyWi** [comment]
> 
> 
> The error "Certificate "4120" can be bypassed by manual installation.
> 
> Go on folder apps
> sudo rm -Rf passman
> sudo wget https://github.com/nextcloud/passman/archive/2.2.1.zip
> sudo unzip 2.2.1.zip
> sudo mv passman-2.2.1 passman
> sudo chmod -Rf 755 passman
> sudo chown -Rf www-data:www-data passman
> 
> Go on application and active extension.
> Done!

Unfortunately, does not work on a NextCloudPi setup. The app still appears as "uninstalled" in the applications list and the Certificate 4120 has been revoked is still here as well.

**Comment by thenotec** [comment]
@RemyWi 
sudo -u www-data php -f occ app:disable passman

See https://tobias.jarvelov.se/2015/02/12/quickly-disableenable-owncloud-app-using-command-line/

**Comment by ezaquarii** [comment]
Is this project abandoned?
The certificate issue - apparently easy to fix by releasing new version - is not fixed for 6 months.

Judging from the maintainer github history, he's no longer involved in open source development.

This project has core 2 maintainers and I think @brantje should give way to more involved members of the community.

**Comment by patrickj0607** [comment]
> The error "Certificate "4120" can be bypassed by manual installation.
> 
> Go on folder apps
> sudo rm -Rf passman
> sudo wget https://github.com/nextcloud/passman/archive/2.2.1.zip
> sudo unzip 2.2.1.zip
> sudo mv passman-2.2.1 passman
> sudo chmod -Rf 755 passman
> sudo chown -Rf www-data:www-data passman
> 
> Go on application and active extension.
> Done!

What are the implications of this described workaround? Does the extensions not receive any auto-updates in this case?

**Comment by thenotec** [comment]
@patrickj0607 why do you think there must be implications for manually installing an extension?!?

**Comment by patrickj0607** [comment]
> @patrickj0607 why do you think there must be implications for manually installing an extension?!?

Because it's not the usual way of installing an extension for Nextcloud. That's why I am asking if there are any implications. So are there any implications (e.g. for future updates) or is the web-based installation just for convenience?

**Comment by dersch81** [comment]
With NC 16 it seems the app doesn't start anymore. 

`Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "passman.page.index" as such route does not exist.`

**Comment by ion-lane** [comment]
I have the same problem since NC14, NC15, and now on version NC16.
Reinstalling the passman does not help.

**Comment by fyah** [comment]
Hello,

still the same issue after upgrade to passman 2.3.0

**Comment by jans23** [comment]
My solution is, I migrated to the [Passwords](https://apps.nextcloud.com/apps/passwords) app which is even easier to use.

**Comment by linuxpronl** [comment]
> My solution is, I migrated to the [Passwords](https://apps.nextcloud.com/apps/passwords) app which is even easier to use.

And how do you intergrate the passwords app in a browser like passman?

**Comment by jans23** [comment]
I just had to install "Passwords" app and it appears in the top menu
such as Passman does.

**Comment by thenotec** [comment]
@linuxpronl 
I think you asked for this
https://git.mdns.eu/nextcloud/passwords/wikis/users/index#browser-extension

**Comment by linuxpronl** [comment]
> @linuxpronl
> I think you asked for this
> https://git.mdns.eu/nextcloud/passwords/wikis/users/index#browser-extension

thanks, I'll give it a try, but it seems it doesn't do autofill at the login forms I tried.

**Comment by iacchi** [comment]
> Hello,
> 
> still the same issue after upgrade to passman 2.3.0

I can confirm this. Running NC 16 and just updated to v. 2.3.0, the problem is still there.

**Comment by animalillo** [comment]
This has been fixed on v2.3.1 in the oficial nextcloud store.
