### ISSUE TITLE
[Critical] Vault Cannot be Created with Passman - 500 Server Error

### ISSUE THREAD

**Issue by wshen001** [nextcloud/passman#726]
### Steps to reproduce
1. Install the latest Nextcloud version. 22.1.1
2. Install Passman v2.3.1334	
3. Create a vault in Passman and issue happened

### Expected behaviour
Vault should be created correctly.

### Actual behaviour
When I tried to create a vault, I see a POST request sending to /apps/passman/api/v2/credentials, however, the server (the app) always returns a 500 error

### Configuration
**Operating system**:   Ubuntu 20.04

**Browser**:  Chrome, Firefox

**Extensions that might cause interference**:   

**Passman version**:   v2.3.1334

**Operating system**: Ubuntu 20.04

**Web server:** Apache v2.4.41

**Database:** MySQL 10.3.31

**PHP version:** v7.4.3
      
**cloud server:** Nextcloud

**cloud version:** v22.1.1

![Screen Shot 2021-09-29 at 10 25 43 AM](https://user-images.githubusercontent.com/44985256/135289552-818869bb-6d9e-4235-a7c4-bffdca8157c9.png)
![Screen Shot 2021-09-29 at 10 27 45 AM](https://user-images.githubusercontent.com/44985256/135289563-b7759e64-dc12-4c2d-920f-0fc229aaf165.png)
![Screen Shot 2021-09-29 at 10 27 56 AM](https://user-images.githubusercontent.com/44985256/135289581-d92d71b4-70e8-44c2-a7d9-43b234723a6f.png)

   
#### Browser log
![image](https://user-images.githubusercontent.com/44985256/135342393-6ddb8846-a583-4291-867b-754b811379a4.png)

<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by binsky08** [comment]
@wshen001 I was not able to reproduce that on my system.
Could you please append the nextcloud log output which appears when you try to create a vault. It's usually logged in the nextcloud.log file in the configured data directory.

**Comment by wshen001** [comment]
@binsky08  thank you for checking the issue for me. I just uploaded a screenshot of errors I found in logs.

**Comment by wshen001** [comment]
Seems like when Passman tried to save the credential, there's an exception occurred, something like `Unknown column icon in field list`.

**Comment by binsky08** [comment]
hmm, found out that in 2017 the column favicon changed to icon in the source code.
I couldn't find a database migration for this, but that was before my time, so I'm not sure if there was one before.

Please answer the following questions as far as possible
- How old is your Passman installation? (when have you installed Passman the first time with your current Nextcloud database)
- Could you take a look at your Nextcloud database and tell me if there is a column `icon` or `favicon` in the `passman_credentials` table?
- Was it possible for you to create vaults before the update to Passman v2.3.1334? and was it possible to create new credentials?
  - if it was possible, which version of Passman was installed before?

**Comment by wshen001** [comment]
@binsky08  exactly, we have been upgraded from nextcloud version 13 to the latest version 22. Our previous passman is in version `2.1.4`. So after I finished the upgrade of nextcloud to ver.22, I update the passman, (from 2.1.4 to 2.3.1334)

**Comment by wshen001** [comment]
@binsky08  Hopefully all these information would help:
- We installed our passman 2.1.4 four years ago with Nextcloud version 13.
- I have checked columns of `passman_credentials`, I only see `favicon`. 
- Yes, passman works fine before we upgrade the nextcloud. It was version 2.1.4.

**Comment by binsky08** [comment]
thanks, that's what I suspected. the missing intermediate updates probably caused the problem with the column that was not changed. I will write a migration for the column tomorrow that will be included in the next update. maybe I can find other changed columns with missing migration.

**Comment by wshen001** [comment]
@binsky08 thank you for the help. 

Here is the structure of `oc_passman_credentials` table in passman `2.1.4`:
<img width="587" alt="passman_2 1 4_credential_structure" src="https://user-images.githubusercontent.com/44985256/135365147-7610db07-1512-4103-b602-975f34b40299.png">

And, here is the latest structure in the version `2.3.1334`:
<img width="574" alt="passman_2 3 1334_credential_structure" src="https://user-images.githubusercontent.com/44985256/135365180-7b596b3c-938f-4042-849d-7604499c86e3.png">

Hopefully, it can help you clarify the migration updates. And I look forward to seeing the new updated version. :)

**Comment by wshen001** [comment]
@binsky08  Just wondering if you are able to add missing intermediate updates? We are hoping to see get an official fix from the passman team. We have some users still not able to retrieve their passwords after we upgraded to the latest nextcloud.

**Comment by animalillo** [comment]
I have just published a hotfix release, please, check if @binsky08 fix solves your problem
https://github.com/nextcloud/passman/releases/tag/2.3.1335

**Comment by wshen001** [comment]
@animalillo  thank you so much for the help. I have seen the release tag. Could you tell me how long will it take to see the updated version is available in the NextCloud admin portal?

**Comment by binsky08** [comment]
> @animalillo  thank you so much for the help. I have seen the release tag. Could you tell me how long will it take to see the updated version is available in the NextCloud admin portal? 

Should be available within an hour.

**Comment by wshen001** [comment]
@binsky08  I have installed the updated version of Passman. But it seems like the migration doesn't happen? I still see 500 server error. How to trigger the app to perform the migration?

**Comment by binsky08** [comment]
> @binsky08  @animalillo  I have installed the updated version of Passman. But it seems like the migration doesn't happen? I still see 500 server error. How to trigger the app to perform the migration?

try to disable it and enable it again using the console occ command.
Like `sudo -u www-data php occ apps:disable passman`

**Comment by wshen001** [comment]
@binsky08  I tried with the console command, but unfortunately, it does not trigger the migration...

**Comment by wshen001** [comment]
should I perform a manual table definition change?

**Comment by binsky08** [comment]
> should I perform a manual table definition change? 

you can simply try to rename the column favicon to icon.
But I do not understand why the migration does not work for you.

**Comment by wshen001** [comment]
> > should I perform a manual table definition change?
> 
> you can simply try to rename the column favicon to icon. But I do not understand why the migration does not work for you.

Maybe it's because my nextcloud is already version 22? Today I updated the passman through the admin portal directly. I didn't do the upgrade from the commandline. Not sure if it matters? I thought the migration would work, not sure why..

**Comment by wshen001** [comment]
@bingen  Sorry, I double checked the table of `passman_crendential`, looks like the favicon has been migrated to icon. However, there's another error preventing the credential created successfully, here is the log:

```{"reqId":"ewcpttncUKAgQywIduw4","level":3,"time":"2021-10-02T20:11:29+00:00","remoteAddr":"24.103.126.108","user":"26e42422-980b-1038-8c2f-6b811f5b5a06","app":"index","method":"POST","url":"/apps/passman/api/v2/credentials","message":"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'compromised' in 'field list'","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0","version":"22.1.1.2","exception":{"Exception":"OC\\DB\\Exceptions\\DbalException","Message":"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'compromised' in 'field list'","Code":1054,"Trace":[{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":335,"function":"wrap","class":"OC\\DB\\Exceptions\\DbalException","type":"::"},{"file":"/var/www/html/lib/public/AppFramework/Db/QBMapper.php","line":139,"function":"executeStatement","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Db/CredentialMapper.php","line":174,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Service/CredentialService.php","line":61,"function":"create","class":"OCA\\Passman\\Db\\CredentialMapper","type":"->"},{"file":"/var/www/html/apps2/passman/controller/credentialcontroller.php","line":98,"function":"createCredential","class":"OCA\\Passman\\Service\\CredentialService","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"createCredential","class":"OCA\\Passman\\Controller\\CredentialController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/DB/Exceptions/DbalException.php","Line":71,"Previous":{"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'compromised' in 'field list'","Code":1054,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1146,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":333,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/lib/public/AppFramework/Db/QBMapper.php","line":139,"function":"executeStatement","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Db/CredentialMapper.php","line":174,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Service/CredentialService.php","line":61,"function":"create","class":"OCA\\Passman\\Db\\CredentialMapper","type":"->"},{"file":"/var/www/html/apps2/passman/controller/credentialcontroller.php","line":98,"function":"createCredential","class":"OCA\\Passman\\Service\\CredentialService","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"createCredential","class":"OCA\\Passman\\Controller\\CredentialController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":65,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'compromised' in 'field list'","Code":1054,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":333,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/lib/public/AppFramework/Db/QBMapper.php","line":139,"function":"executeStatement","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Db/CredentialMapper.php","line":174,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Service/CredentialService.php","line":61,"function":"create","class":"OCA\\Passman\\Db\\CredentialMapper","type":"->"},{"file":"/var/www/html/apps2/passman/controller/credentialcontroller.php","line":98,"function":"createCredential","class":"OCA\\Passman\\Service\\CredentialService","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"createCredential","class":"OCA\\Passman\\Controller\\CredentialController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'compromised' in 'field list'","Code":"42S22","Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":333,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/lib/public/AppFramework/Db/QBMapper.php","line":139,"function":"executeStatement","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Db/CredentialMapper.php","line":174,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/html/apps2/passman/lib/Service/CredentialService.php","line":61,"function":"create","class":"OCA\\Passman\\Db\\CredentialMapper","type":"->"},{"file":"/var/www/html/apps2/passman/controller/credentialcontroller.php","line":98,"function":"createCredential","class":"OCA\\Passman\\Service\\CredentialService","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"createCredential","class":"OCA\\Passman\\Controller\\CredentialController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}}},"CustomMessage":"--"}}```

**Comment by wshen001** [comment]
This is a new error I have seen, looks like there's a missing column `compromised` that should be in the table called `compromised`?

**Comment by wshen001** [comment]
@binsky08  I see this change in 2019 (https://github.com/nextcloud/passman/commit/deee11f454548d22d11fc90f0eab09d52bb1f7a3#diff-25f7ce47fa1ac45fc7885a9201cad1e81a946f9a5ff601c56267ca77e2d8e512), the credential table added compromised column.  If my passman table is migrated from the old version, should I simply add this column `compromised`? But what type?

**Comment by binsky08** [comment]
@wshen001 I'm so sorry, that you have so many problems with the passman database.
I am since about one year on this project and tried to improve many things. But I have no idea, how database migrations were made before. 
I hope these database problems are an isolated incident.
If you take a look into the existing migrations at lib/Migration you should be able to fix your db setup. 

If it helps, I add the mysql describe output of the current passman tables:

```
MariaDB [oc_autotest]> describe oc_passman_credentials;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| id             | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| guid           | varchar(64)         | YES  |     | NULL    |                |
| user_id        | varchar(64)         | YES  | MUL | NULL    |                |
| vault_id       | bigint(20)          | NO   | MUL | NULL    |                |
| label          | varchar(2048)       | NO   |     | NULL    |                |
| description    | longtext            | YES  |     | NULL    |                |
| created        | bigint(20) unsigned | YES  |     | 0       |                |
| changed        | bigint(20) unsigned | YES  |     | 0       |                |
| tags           | longtext            | YES  |     | NULL    |                |
| email          | longtext            | YES  |     | NULL    |                |
| username       | longtext            | YES  |     | NULL    |                |
| password       | longtext            | YES  |     | NULL    |                |
| url            | longtext            | YES  |     | NULL    |                |
| renew_interval | bigint(20) unsigned | YES  |     | NULL    |                |
| expire_time    | bigint(20) unsigned | YES  |     | NULL    |                |
| delete_time    | bigint(20) unsigned | YES  |     | NULL    |                |
| files          | longtext            | YES  |     | NULL    |                |
| custom_fields  | longtext            | YES  |     | NULL    |                |
| otp            | longtext            | YES  |     | NULL    |                |
| hidden         | tinyint(1)          | YES  |     | 0       |                |
| compromised    | longtext            | YES  |     | NULL    |                |
| shared_key     | longtext            | YES  |     | NULL    |                |
| icon           | longtext            | YES  |     | NULL    |                |
+----------------+---------------------+------+-----+---------+----------------+
23 rows in set (0.001 sec)

MariaDB [oc_autotest]> describe oc_passman_delete_vault_request;
+--------------+---------------------+------+-----+---------+----------------+
| Field        | Type                | Null | Key | Default | Extra          |
+--------------+---------------------+------+-----+---------+----------------+
| id           | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| vault_guid   | varchar(64)         | NO   |     | NULL    |                |
| reason       | varchar(64)         | NO   |     | NULL    |                |
| requested_by | varchar(64)         | YES  |     | NULL    |                |
| created      | bigint(20) unsigned | YES  |     | 0       |                |
+--------------+---------------------+------+-----+---------+----------------+
5 rows in set (0.001 sec)

MariaDB [oc_autotest]> describe oc_passman_files;
+-----------+---------------------+------+-----+---------+----------------+
| Field     | Type                | Null | Key | Default | Extra          |
+-----------+---------------------+------+-----+---------+----------------+
| id        | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| guid      | varchar(64)         | YES  |     | NULL    |                |
| user_id   | varchar(64)         | YES  | MUL | NULL    |                |
| mimetype  | varchar(255)        | NO   |     | NULL    |                |
| filename  | longtext            | NO   |     | NULL    |                |
| size      | bigint(20)          | NO   |     | NULL    |                |
| created   | bigint(20)          | NO   |     | NULL    |                |
| file_data | longtext            | YES  |     | NULL    |                |
+-----------+---------------------+------+-----+---------+----------------+
8 rows in set (0.001 sec)

MariaDB [oc_autotest]> describe oc_passman_revisions;
+-----------------+---------------------+------+-----+---------+----------------+
| Field           | Type                | Null | Key | Default | Extra          |
+-----------------+---------------------+------+-----+---------+----------------+
| id              | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| guid            | varchar(64)         | NO   |     | NULL    |                |
| credential_id   | bigint(20)          | NO   | MUL | NULL    |                |
| user_id         | varchar(64)         | NO   | MUL | NULL    |                |
| created         | bigint(20) unsigned | YES  |     | 0       |                |
| credential_data | longtext            | NO   |     | NULL    |                |
| edited_by       | varchar(64)         | NO   |     | NULL    |                |
+-----------------+---------------------+------+-----+---------+----------------+
7 rows in set (0.001 sec)

MariaDB [oc_autotest]> describe oc_passman_share_request;
+-------------------+----------------------+------+-----+---------+----------------+
| Field             | Type                 | Null | Key | Default | Extra          |
+-------------------+----------------------+------+-----+---------+----------------+
| id                | bigint(20) unsigned  | NO   | PRI | NULL    | auto_increment |
| item_id           | bigint(20)           | NO   |     | NULL    |                |
| item_guid         | varchar(64)          | NO   |     | NULL    |                |
| target_user_id    | varchar(64)          | YES  |     | NULL    |                |
| from_user_id      | varchar(64)          | YES  |     | NULL    |                |
| target_vault_id   | bigint(20) unsigned  | NO   |     | NULL    |                |
| target_vault_guid | varchar(64)          | NO   |     | NULL    |                |
| shared_key        | longtext             | NO   |     | NULL    |                |
| permissions       | smallint(5) unsigned | NO   |     | 0       |                |
| created           | bigint(20) unsigned  | YES  |     | 0       |                |
+-------------------+----------------------+------+-----+---------+----------------+
10 rows in set (0.001 sec)

MariaDB [oc_autotest]> describe oc_passman_sharing_acl;
+--------------+----------------------+------+-----+---------+----------------+
| Field        | Type                 | Null | Key | Default | Extra          |
+--------------+----------------------+------+-----+---------+----------------+
| id           | bigint(20) unsigned  | NO   | PRI | NULL    | auto_increment |
| item_id      | bigint(20)           | NO   |     | NULL    |                |
| item_guid    | varchar(64)          | NO   |     | NULL    |                |
| vault_id     | bigint(20) unsigned  | YES  |     | NULL    |                |
| vault_guid   | varchar(64)          | YES  |     | NULL    |                |
| user_id      | varchar(64)          | YES  |     | NULL    |                |
| created      | bigint(20) unsigned  | YES  |     | 0       |                |
| expire       | bigint(20) unsigned  | YES  |     | 0       |                |
| expire_views | bigint(20) unsigned  | YES  |     | 0       |                |
| permissions  | smallint(5) unsigned | NO   |     | 0       |                |
| shared_key   | longtext             | YES  |     | NULL    |                |
+--------------+----------------------+------+-----+---------+----------------+
11 rows in set (0.001 sec)

MariaDB [oc_autotest]> describe oc_passman_vaults;
+------------------------+---------------------+------+-----+---------+----------------+
| Field                  | Type                | Null | Key | Default | Extra          |
+------------------------+---------------------+------+-----+---------+----------------+
| id                     | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| guid                   | varchar(64)         | NO   | MUL |         |                |
| user_id                | varchar(64)         | NO   | MUL |         |                |
| name                   | varchar(100)        | NO   |     | NULL    |                |
| vault_settings         | longtext            | YES  |     | NULL    |                |
| created                | bigint(20) unsigned | YES  |     | 0       |                |
| last_access            | bigint(20) unsigned | YES  | MUL | 0       |                |
| public_sharing_key     | longtext            | YES  |     | NULL    |                |
| private_sharing_key    | longtext            | YES  |     | NULL    |                |
| sharing_keys_generated | bigint(20)          | YES  |     | NULL    |                |
+------------------------+---------------------+------+-----+---------+----------------+
10 rows in set (0.001 sec)

```

**Comment by wshen001** [comment]
@binsky08  I got it working when I add a column of "compromised" into the table. Thank you!
